"""add rents

Revision ID: f2b0972b1a5e
Revises: 53d0364534b1
Create Date: 2023-12-31 19:39:58.562326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b0972b1a5e'
down_revision: Union[str, None] = '53d0364534b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=True),
    sa.Column('rent_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rents')
    # ### end Alembic commands ###
